### a) Ler o dataset fakeTelegram.BR_2022.csv, o qual está disponível no link a seguir: https://drive.google.com/file/d/1c_hLzk85pYw-huHSnFYZM_gndUsYRDm/view?usp=drive_link

In [10]:
import pandas as pd

# Define o nome do arquivo a ser lido
file_path = 'fakeTelegram.BR_2022_short.csv'

df = pd.read_csv(file_path)

In [11]:
df.head()

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637

### b) Remova os trava-zaps, as linhas repetidas (duplicadas) e textos com menos de 5 palavras.

In [12]:
print("Removendo trava-zaps...")
df_limpo = df[df['trava_zap'] == False].copy()
print(f"Formato após remover trava-zaps: {df_limpo.shape}")

print("Removendo mensagens duplicadas (baseado no conteúdo do texto)...")
df_limpo.drop_duplicates(subset=['text_content_anonymous'], inplace=True)
print(f"Formato após remover duplicatas: {df_limpo.shape}")

print("Removendo mensagens com menos de 5 palavras...")
condicao_palavras = (df_limpo['text_content_anonymous'].isna()) | (df_limpo['text_content_anonymous'].str.split().str.len() >= 5)
df_limpo = df_limpo[condicao_palavras]

df_limpo.head()

Removendo trava-zaps...
Formato após remover trava-zaps: (601, 19)
Removendo mensagens duplicadas (baseado no conteúdo do texto)...
Formato após remover duplicatas: (432, 19)
Removendo mensagens com menos de 5 palavras...

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637

### c) Agrupe as linhas com postagens iguais ou extremamente semelhantes. Aqui você pode utilizar uma métrica de semelhança de textos. Crie uma variável para representar a quantidade de vezes que a mensagem foi compartilhada. Observe que ao agrupar linhas que possuem a “mesma” postagem (texto), você deve escolher como valor para as variáveis data e hora da postagem, os valores da cópia mais antiga.

In [13]:
# Importando as bibliotecas necessárias para a tarefa
from thefuzz import process, fuzz
import pandas as pd

# --- Etapa 1: Preparação Adicional dos Dados ---
# O seu código já criou 'df_limpo'. Vamos garantir que os tipos de dados estão corretos para a operação.

# Garantir que a coluna de data esteja no formato datetime para podermos encontrar a mais antiga
df_limpo['date_message'] = pd.to_datetime(df_limpo['date_message'])

# Preencher possíveis valores nulos (NaN) na coluna de texto para evitar erros no processamento
df_limpo['text_content_anonymous'] = df_limpo['text_content_anonymous'].fillna('')

# Criar uma cópia de trabalho para evitar o SettingWithCopyWarning do pandas
df_to_process = df_limpo.copy()


# --- Etapa 2: Lógica de Agrupamento por Similaridade (VERSÃO CORRIGIDA) ---

# Limiar de similaridade. Textos com 90% ou mais de semelhança serão agrupados.
SIMILARITY_THRESHOLD = 90

# Armazena os clusters (grupos) de mensagens similares.
clusters = []
# Guarda os índices que já foram agrupados para não os processarmos novamente.
processed_indices = set()

# Criar um dicionário (índice -> texto) é mais eficiente para a busca.
choices_dict = df_to_process['text_content_anonymous'].to_dict()

print(f"Iniciando o agrupamento por similaridade para {len(df_to_process)} mensagens...")

for index, row in df_to_process.iterrows():
    # Pula a mensagem se ela já foi adicionada a um grupo
    if index in processed_indices:
        continue

    # Usa o texto da linha atual como consulta para encontrar todos os textos similares no dataset
    query_text = row['text_content_anonymous']
    
    # CORREÇÃO: Usar 'process.extractBests' que aceita 'score_cutoff'.
    # Adicionamos 'limit=None' para obter todos os resultados que atendem ao critério.
    similar_texts = process.extractBests(
        query_text, 
        choices_dict, 
        scorer=fuzz.ratio, 
        score_cutoff=SIMILARITY_THRESHOLD,
        limit=None
    )

    # Extrai apenas os índices do DataFrame das mensagens que formam o cluster
    current_cluster_indices = [idx for text, score, idx in similar_texts]
    
    # Adiciona o novo grupo à nossa lista de clusters
    if current_cluster_indices:
        clusters.append(current_cluster_indices)

        # Marca todos os índices deste novo grupo como processados para não os checar novamente
        processed_indices.update(current_cluster_indices)

print(f"Agrupamento concluído. Encontrados {len(clusters)} grupos de mensagens únicas/similares.")

# --- Etapa 3: Processando os Grupos e Criando o DataFrame Final ---

final_rows = []

for cluster_indices in clusters:
    # Seleciona todas as linhas do DataFrame original que pertencem ao grupo atual
    cluster_df = df_to_process.loc[cluster_indices]
    
    # Encontra o índice da mensagem MAIS ANTIGA no grupo
    oldest_index = cluster_df['date_message'].idxmin()
    
    # Usa a linha da mensagem mais antiga como a representante do grupo
    representative_row = cluster_df.loc[oldest_index].copy()
    
    # Cria a nova coluna com a contagem de compartilhamentos (o tamanho do grupo)
    representative_row['share_count'] = len(cluster_df)
    
    # Adiciona a linha representativa à nossa lista de resultados
    final_rows.append(representative_row)

# Cria o DataFrame final com os resultados agrupados
df_agrupado = pd.DataFrame(final_rows)

# Ordena o resultado pela data e reseta o índice para um resultado limpo
df_agrupado = df_agrupado.sort_values('date_message').reset_index(drop=True)


# --- Etapa 4: Exibindo o Resultado ---

print("\n--- DataFrame Final Agrupado ---")
# Exibindo as colunas mais relevantes para verificação do resultado
display_cols = ['date_message', 'share_count', 'text_content_anonymous']
print(df_agrupado[display_cols].head())

# Para ver um exemplo de mensagens que foram efetivamente agrupadas
print("\nExemplo de mensagens que foram agrupadas (com contagem de compartilhamento > 1):")
print(df_agrupado[df_agrupado['share_count'] > 1][display_cols])

Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

Iniciando o agrupamento por similaridade para 373 mensagens...
Agrupamento concluído. Encontrados 362 grupos de mensagens únicas/similares.

--- DataFrame Final Agrupado ---
         date_message  share_count  \
0 2022-10-05 06:25:04            1
1 2022-10-05 06:25:08            1
2 2022-10-05 06:26:28            1
3 2022-10-05 06:27:28            1
4 2022-10-05 06:27:44            1

                              text_content_anonymous
0  Então é Fato Renato o áudio que eu ouvi no wha...
1  Saiu no YouTube do presidente a 8 horas atrás,...
2  É isso, nossa parte já foi quase toda feita. N...
3           GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA
4

Exemplo de mensagens que foram agrupadas (com contagem de compartilhamento > 1):
           date_message  share_count  \
7   2022-10-05 06:29:48            3
11  2022-10-05 06:35:42            2
14  2022-10-05 06:43:51            2
15  2022-10-05 06:43:51            2
48  2022-10-05 07:46:49            3
59  2022-10-05 08:00:49            2
60  2022-10-05 08:00:51            2
61  2022-10-05 08:00:52            2
231 2022-10-05 09:42:08            2

                                text_content_anonymous
7    O Deputado Federal pelo NOVO e que foi candida...
11   🚨Olá SEJA bem vindo(a) ..- ao grupo Especuland...
14   Feedback de Gabriel De Sousa 24 anos. Brazil, ...
15   Feedback de Mateus Alves\r\n29 anos. Brasil, P...
48   BOA NOITE A TODOS. O QUE EU VOU DIZER É SÉRIO ...
59   #panorama [USER]\r\n\r\n▪️ 05/10/2022 - 05:00 ...
60   #panorama [USER] \r\n #commodities \r\n▪️ 05/1...
61   #panorama [USER] \r\n #criptomoedas \r\n▪️ 05/...
231  Feedback de Cláudio Castilho 28 anos. Brazil, ...

In [14]:
df_agrupado.head()

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5,share_count
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN,1
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN,1
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN,1
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,1
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,1

### d) Você pode criar novos atributos numéricos, tais como: quantidade de palavras, quantidade de caracteres etc.

In [15]:
import string # Biblioteca necessária para a contagem de pontuação

# --- Etapa 5: Criação de Novos Atributos Numéricos ---
# Usando o DataFrame 'df_agrupado' da célula anterior.

print("Criando novos atributos numéricos a partir do texto...")

# 1. Quantidade de Caracteres: O tamanho total da string.
df_agrupado['char_count'] = df_agrupado['text_content_anonymous'].str.len()

# 2. Quantidade de Palavras: Divide o texto por espaços e conta o número de elementos.
# O fillna(0) trata casos onde o texto pode ser nulo (apesar de termos tratado antes, é uma boa prática).
df_agrupado['word_count'] = df_agrupado['text_content_anonymous'].str.split().str.len().fillna(0).astype(int)

# 3. Comprimento Médio da Palavra: Pode indicar a complexidade do vocabulário.
# Dividimos o total de caracteres pelo total de palavras.
# Usamos um truque para evitar a divisão por zero para mensagens sem palavras.
df_agrupado['avg_word_length'] = df_agrupado['char_count'] / df_agrupado['word_count']
# Substitui possíveis valores infinitos ou nulos (resultantes da divisão por 0) por 0.
df_agrupado['avg_word_length'].fillna(0, inplace=True)

# 4. Contagem de Pontuação: Conta o número de caracteres de pontuação.
# Pode ser um indicador de tom ou urgência (ex: "!!!", "???").
df_agrupado['punctuation_count'] = df_agrupado['text_content_anonymous'].apply(
    lambda text: sum(1 for char in text if char in string.punctuation)
)

# 5. Proporção de Letras Maiúsculas: Indica ênfase ou "grito".
# Um valor alto é comum em correntes e mensagens de desinformação.
df_agrupado['uppercase_ratio'] = df_agrupado['text_content_anonymous'].apply(
    lambda text: sum(1 for char in text if char.isupper()) / len(text) if len(text) > 0 else 0
)


# --- Exibindo o Resultado ---
print("Novos atributos criados com sucesso!")

# Seleciona as colunas originais mais relevantes e as novas colunas para uma visualização clara
display_cols = [
    'text_content_anonymous',
    'share_count',
    'char_count',
    'word_count',
    'avg_word_length',
    'punctuation_count',
    'uppercase_ratio'
]

# Mostra as primeiras 5 linhas do DataFrame com as novas colunas
print("\n--- DataFrame com Novos Atributos ---")
print(df_agrupado[display_cols].head())

# Mostra estatísticas descritivas das novas colunas para ter uma ideia da distribuição
print("\n--- Estatísticas Descritivas dos Novos Atributos ---")
print(df_agrupado[display_cols[2:]].describe())

Criando novos atributos numéricos a partir do texto...
Novos atributos criados com sucesso!

--- DataFrame com Novos Atributos ---
                              text_content_anonymous  share_count  char_count  \
0  Então é Fato Renato o áudio que eu ouvi no wha...            1         110
1  Saiu no YouTube do presidente a 8 horas atrás,...            1         141
2  É isso, nossa parte já foi quase toda feita. N...            1         350
3           GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA            1          40
4                                                               1           0

   word_count  avg_word_length  punctuation_count  uppercase_ratio
0          20         5.500000                  1         0.045455
1          23         6.130435                  2         0.035461
2          59         5.932203                  9         0.017143
3           7         5.714286                  0         0.850000
4           0         0.000000                  0         0.000000

--- Estatísticas Descritivas dos Novos Atributos ---
        char_count   word_count  avg_word_length  punctuation_count  \
count   362.000000   362.000000       362.000000         362.000000
mean    469.477901    77.961326         6.447925          16.715470
std     817.375650   149.642987         1.826455          31.127372
min       0.000000     0.000000         0.000000           0.000000
25%     117.000000    19.000000         5.572407           2.000000
50%     169.500000    28.000000         6.000000           6.000000
75%     372.250000    55.750000         6.652369          17.000000
max    4208.000000  1261.000000        17.647059         212.000000

       uppercase_ratio
count       362.000000
mean          0.095312
std           0.172880
min           0.000000
25%           0.017991
50%           0.033445
75%           0.069439
max           0.850000

C:\Users\jose.junior\AppData\Local\Temp\ipykernel_10696\3202700260.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_agrupado['avg_word_length'].fillna(0, inplace=True)

In [16]:
df_agrupado.head()

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,message_type,messenger,media_name,media_md5,share_count,char_count,word_count,avg_word_length,punctuation_count,uppercase_ratio
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,Texto,telegram,NaN,NaN,1,110,20,5.500000,1,0.045455
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,Texto,telegram,NaN,NaN,1,141,23,6.130435,2,0.035461
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,Texto,telegram,NaN,NaN,1,350,59,5.932203,9,0.017143
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,1,40,7,5.714286,0,0.850000
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,,...,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,1,0,0,0.000000,0,0.000000

### Questão 1
### Utilizando os dados referente a postagens no Telegram, crie um modelo preditivo (classificador binário) para classificar uma mensagem em duas classes possíveis: “viral” (classe positiva) ou “não viral” (classe negativa). Para rotular as mensagens únicas (agrupadas) nas classes, “viral” e “não viral”, utilize a seguinte estratégia: Calcule um limiar (threshold). Por exemplo, mediana do número de compartilhamentos mais dois desvios padrões. As mensagens com quantidade de compartilhamentos maiores ou iguais ao limiar definido devem ser rotuladas como “virais”. As demais mensagens devem ser rotuladas como “não virais”.

In [21]:
import pandas as pd
import numpy as np
import string
import nltk

# Importando componentes do Scikit-learn
from sklearn.model_selection import KFold
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from scipy.sparse import hstack

# Importando componentes para pré-processamento de texto
from nltk.corpus import stopwords
from nltk.stem import RSLPStemmer

try:
    # Checa se as stopwords para português estão disponíveis
    stopwords.words('portuguese')
except LookupError:
    print("Baixando o recurso 'stopwords' do NLTK...")
    nltk.download('stopwords')

try:
    # Tenta instanciar o stemmer para forçar a verificação do recurso 'rslp'
    RSLPStemmer()
except LookupError:
    print("Baixando o recurso 'rslp' do NLTK...")
    nltk.download('rslp')

print("Recursos do NLTK estão prontos.")

# ==============================================================================
# 1. DEFINIÇÃO DA VARIÁVEL ALVO (VIRAL / NÃO VIRAL)
# ==============================================================================
print("--- 1. Definindo a variável alvo 'is_viral' ---")

share_median = df_agrupado['share_count'].median()
share_std = df_agrupado['share_count'].std()
threshold = share_median + (2 * share_std)

print(f"Mediana de compartilhamentos: {share_median:.2f}")
print(f"Desvio Padrão de compartilhamentos: {share_std:.2f}")
print(f"Limiar de Viralização (threshold) calculado: {threshold:.2f}")

df_agrupado['is_viral'] = (df_agrupado['share_count'] >= threshold).astype(int)

print("\nDistribuição das classes:")
print(df_agrupado['is_viral'].value_counts())

if len(df_agrupado['is_viral'].unique()) < 2:
    raise ValueError("O limiar resultou em apenas uma classe. Não é possível treinar um classificador.")

print("\nVariável alvo criada com sucesso.")


# ==============================================================================
# 2. FUNÇÕES AUXILIARES E PRÉ-PROCESSAMENTO (Item h)
# ==============================================================================
print("\n--- 2. Definindo funções de pré-processamento de texto ---")

stop_words_pt = set(stopwords.words('portuguese'))
stemmer_pt = RSLPStemmer()

def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = ''.join([char for char in text if char not in string.punctuation])
    tokens = [word for word in text.split() if word not in stop_words_pt]
    stemmed_tokens = [stemmer_pt.stem(word) for word in tokens]
    return ' '.join(stemmed_tokens)

# ### ALTERAÇÃO ###: A função "w2v_vectorizer" foi completamente removida.

# ==============================================================================
# 3. DEFINIÇÃO DO EXPERIMENTO (Itens e, f, g, i, j, k)
# ==============================================================================
print("\n--- 3. Definindo o setup do experimento de classificação ---")

NUMERICAL_FEATURES = ['char_count', 'word_count', 'avg_word_length', 'punctuation_count', 'uppercase_ratio']
TEXT_FEATURE = 'text_content_anonymous'

X = df_agrupado[NUMERICAL_FEATURES + [TEXT_FEATURE]]
y = df_agrupado['is_viral']

outer_cv = KFold(n_splits=5, shuffle=True, random_state=42)
results_list = []

# --- Definindo as combinações a serem testadas ---

MODELS_TO_TEST = {
    'LogisticRegression_NoReg': LogisticRegression(penalty=None, max_iter=1000), # <--- CORRIGIDO
    'LogisticRegression_L1': LogisticRegression(penalty='l1', solver='liblinear', C=1.0),
    'LogisticRegression_L2': LogisticRegression(penalty='l2', C=1.0, max_iter=1000),
    'DecisionTree': DecisionTreeClassifier(random_state=42),
    'RandomForest': RandomForestClassifier(random_state=42)
}

SCALERS_TO_TEST = {
    'NoScaler': None,
    'Z-Score': StandardScaler(with_mean=False), # 'with_mean=False' para matrizes esparsas
    'MinMax': MinMaxScaler()
}

PREPROCESSING_TO_TEST = {
    'Sem_Preprocessamento': False,
    'Com_Preprocessamento': True
}

# ### ALTERAÇÃO ###: O dicionário de embeddings foi simplificado, removendo a opção Word2Vec.
EMBEDDINGS_TO_TEST = {
    'BOW_Unigram': ('bow', (1, 1)),
    'BOW_Bigram': ('bow', (1, 2)),
    'BOW_Trigram': ('bow', (1, 3)),
    'TFIDF_Unigram': ('tfidf', (1, 1)),
    'TFIDF_Bigram': ('tfidf', (1, 2)),
    'TFIDF_Trigram': ('tfidf', (1, 3))
}


# ==============================================================================
# 4. EXECUÇÃO DO EXPERIMENTO (LOOP PRINCIPAL)
# ==============================================================================
print("\n--- 4. Iniciando a execução do experimento com Outer K-Fold CV ---")
total_runs = len(MODELS_TO_TEST) * len(SCALERS_TO_TEST) * len(PREPROCESSING_TO_TEST) * len(EMBEDDINGS_TO_TEST)
run_count = 0

for model_name, model in MODELS_TO_TEST.items():
    for scaler_name, scaler in SCALERS_TO_TEST.items():
        for preproc_name, use_preprocessing in PREPROCESSING_TO_TEST.items():
            for embed_name, (embed_type, ngram_range) in EMBEDDINGS_TO_TEST.items():
                
                run_count += 1
                print(f"Executando ({run_count}/{total_runs}): {model_name}, {scaler_name}, {preproc_name}, {embed_name}")
                
                fold_scores = []
                
                for train_idx, test_idx in outer_cv.split(X, y):
                    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
                    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

                    X_train_text = X_train[TEXT_FEATURE]
                    X_test_text = X_test[TEXT_FEATURE]
                    if use_preprocessing:
                        X_train_text = X_train_text.apply(preprocess_text)
                        X_test_text = X_test_text.apply(preprocess_text)
                        
                    if embed_type == 'bow':
                        vectorizer = CountVectorizer(ngram_range=ngram_range)
                        X_train_text_feat = vectorizer.fit_transform(X_train_text)
                        X_test_text_feat = vectorizer.transform(X_test_text)
                    elif embed_type == 'tfidf':
                        vectorizer = TfidfVectorizer(ngram_range=ngram_range)
                        X_train_text_feat = vectorizer.fit_transform(X_train_text)
                        X_test_text_feat = vectorizer.transform(X_test_text)
                    
                    X_train_num_feat = X_train[NUMERICAL_FEATURES].values
                    X_test_num_feat = X_test[NUMERICAL_FEATURES].values
                    if scaler:
                        # Scalers como StandardScaler não funcionam bem com matrizes esparsas diretamente.
                        # Por isso, aplicamos a normalização apenas nas features numéricas antes de juntar.
                        # Esta abordagem foi implicitamente feita antes, mas agora é mais clara.
                        # MinMaxScaler funciona com matrizes esparsas, mas StandardScaler precisa de `with_mean=False`.
                        X_train_num_feat = scaler.fit_transform(X_train_num_feat)
                        X_test_num_feat = scaler.transform(X_test_num_feat)
                        
                    # ### ALTERAÇÃO ###: A lógica de combinação de features foi simplificada.
                    # Como só temos matrizes esparsas (BOW, TF-IDF), usamos hstack em todos os casos.
                    X_train_final = hstack([X_train_text_feat, X_train_num_feat]).tocsr()
                    X_test_final = hstack([X_test_text_feat, X_test_num_feat]).tocsr()

                    model.fit(X_train_final, y_train)
                    y_pred = model.predict(X_test_final)
                    
                    fold_scores.append({
                        'accuracy': accuracy_score(y_test, y_pred),
                        'precision': precision_score(y_test, y_pred, zero_division=0),
                        'recall': recall_score(y_test, y_pred, zero_division=0),
                        'f1': f1_score(y_test, y_pred, zero_division=0)
                    })

                avg_scores = pd.DataFrame(fold_scores).mean().to_dict()
                
                results_list.append({
                    'Modelo': model_name,
                    'Normalizador': scaler_name,
                    'Preprocessamento': preproc_name,
                    'Embedding_Ngram': embed_name,
                    'F1_Score_Medio': avg_scores['f1'],
                    'Precisao_Media': avg_scores['precision'],
                    'Recall_Medio': avg_scores['recall'],
                    'Acuracia_Media': avg_scores['accuracy']
                })

# ==============================================================================
# 5. ANÁLISE DOS RESULTADOS
# ==============================================================================
print("\n--- 5. Análise dos Resultados Finais ---")

results_df = pd.DataFrame(results_list)
results_df_sorted = results_df.sort_values(by='F1_Score_Medio', ascending=False).reset_index(drop=True)

print("As 15 melhores combinações de modelo e parâmetros, ordenadas por F1-Score:")
print(results_df_sorted.head(15).to_string())

Recursos do NLTK estão prontos.
--- 1. Definindo a variável alvo 'is_viral' ---
Mediana de compartilhamentos: 1.00
Desvio Padrão de compartilhamentos: 0.20
Limiar de Viralização (threshold) calculado: 1.40

Distribuição das classes:
is_viral
0    353
1      9
Name: count, dtype: int64

Variável alvo criada com sucesso.

--- 2. Definindo funções de pré-processamento de texto ---

--- 3. Definindo o setup do experimento de classificação ---

--- 4. Iniciando a execução do experimento com Outer K-Fold CV ---
Executando (1/180): LogisticRegression_NoReg, NoScaler, Sem_Preprocessamento, BOW_Unigram
Executando (2/180): LogisticRegression_NoReg, NoScaler, Sem_Preprocessamento, BOW_Bigram
Executando (3/180): LogisticRegression_NoReg, NoScaler, Sem_Preprocessamento, BOW_Trigram
Executando (4/180): LogisticRegression_NoReg, NoScaler, Sem_Preprocessamento, TFIDF_Unigram
Executando (5/180): LogisticRegression_NoReg, NoScaler, Sem_Preprocessamento, TFIDF_Bigram
Executando (6/180): LogisticRegression_NoReg, NoScaler, Sem_Preprocessamento, TFIDF_Trigram
Executando (7/180): LogisticRegression_NoReg, NoScaler, Com_Preprocessamento, BOW_Unigram
Executando (8/180): LogisticRegression_NoReg, NoScaler, Com_Preprocessamento, BOW_Bigram
Executando (9/180): LogisticRegression_NoReg, NoScaler, Com_Preprocessamento, BOW_Trigram
Executando (10/180): LogisticRegression_NoReg, NoScaler, Com_Preprocessamento, TFIDF_Unigram
Executando (11/180): LogisticRegression_NoReg, NoScaler, Com_Preprocessamento, TFIDF_Bigram
Executando (12/180): LogisticRegression_NoReg, NoScaler, Com_Preprocessamento, TFIDF_Trigram
Executando (13/180): LogisticRegression_NoReg, Z-Score, Sem_Preprocessamento, BOW_Unigram
Executando (14/180): LogisticRegression_NoReg, Z-Score, Sem_Preprocessamento, BOW_Bigram
Executando (15/180): LogisticRegression_NoReg, Z-Score, Sem_Preprocessamento, BOW_Trigram
Executando (16/180): LogisticRegression_NoReg, Z-Score, Sem_Preprocessamento, TFIDF_Unigram
Executando (17/180): LogisticRegression_NoReg, Z-Score, Sem_Preprocessamento, TFIDF_Bigram
Executando (18/180): LogisticRegression_NoReg, Z-Score, Sem_Preprocessamento, TFIDF_Trigram
Executando (19/180): LogisticRegression_NoReg, Z-Score, Com_Preprocessamento, BOW_Unigram
Executando (20/180): LogisticRegression_NoReg, Z-Score, Com_Preprocessamento, BOW_Bigram
Executando (21/180): LogisticRegression_NoReg, Z-Score, Com_Preprocessamento, BOW_Trigram
Executando (22/180): LogisticRegression_NoReg, Z-Score, Com_Preprocessamento, TFIDF_Unigram
Executando (23/180): LogisticRegression_NoReg, Z-Score, Com_Preprocessamento, TFIDF_Bigram
Executando (24/180): LogisticRegression_NoReg, Z-Score, Com_Preprocessamento, TFIDF_Trigram
Executando (25/180): LogisticRegression_NoReg, MinMax, Sem_Preprocessamento, BOW_Unigram
Executando (26/180): LogisticRegression_NoReg, MinMax, Sem_Preprocessamento, BOW_Bigram
Executando (27/180): LogisticRegression_NoReg, MinMax, Sem_Preprocessamento, BOW_Trigram
Executando (28/180): LogisticRegression_NoReg, MinMax, Sem_Preprocessamento, TFIDF_Unigram
Executando (29/180): LogisticRegression_NoReg, MinMax, Sem_Preprocessamento, TFIDF_Bigram
Executando (30/180): LogisticRegression_NoReg, MinMax, Sem_Preprocessamento, TFIDF_Trigram
Executando (31/180): LogisticRegression_NoReg, MinMax, Com_Preprocessamento, BOW_Unigram
Executando (32/180): LogisticRegression_NoReg, MinMax, Com_Preprocessamento, BOW_Bigram
Executando (33/180): LogisticRegression_NoReg, MinMax, Com_Preprocessamento, BOW_Trigram
Executando (34/180): LogisticRegression_NoReg, MinMax, Com_Preprocessamento, TFIDF_Unigram
Executando (35/180): LogisticRegression_NoReg, MinMax, Com_Preprocessamento, TFIDF_Bigram
Executando (36/180): LogisticRegression_NoReg, MinMax, Com_Preprocessamento, TFIDF_Trigram
Executando (37/180): LogisticRegression_L1, NoScaler, Sem_Preprocessamento, BOW_Unigram
Executando (38/180): LogisticRegression_L1, NoScaler, Sem_Preprocessamento, BOW_Bigram
Executando (39/180): LogisticRegression_L1, NoScaler, Sem_Preprocessamento, BOW_Trigram
Executando (40/180): LogisticRegression_L1, NoScaler, Sem_Preprocessamento, TFIDF_Unigram

C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Executando (41/180): LogisticRegression_L1, NoScaler, Sem_Preprocessamento, TFIDF_Bigram

C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Executando (42/180): LogisticRegression_L1, NoScaler, Sem_Preprocessamento, TFIDF_Trigram

C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Executando (43/180): LogisticRegression_L1, NoScaler, Com_Preprocessamento, BOW_Unigram
Executando (44/180): LogisticRegression_L1, NoScaler, Com_Preprocessamento, BOW_Bigram
Executando (45/180): LogisticRegression_L1, NoScaler, Com_Preprocessamento, BOW_Trigram
Executando (46/180): LogisticRegression_L1, NoScaler, Com_Preprocessamento, TFIDF_Unigram

C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Executando (47/180): LogisticRegression_L1, NoScaler, Com_Preprocessamento, TFIDF_Bigram

C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Executando (48/180): LogisticRegression_L1, NoScaler, Com_Preprocessamento, TFIDF_Trigram

C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jose.junior\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Executando (49/180): LogisticRegression_L1, Z-Score, Sem_Preprocessamento, BOW_Unigram
Executando (50/180): LogisticRegression_L1, Z-Score, Sem_Preprocessamento, BOW_Bigram
Executando (51/180): LogisticRegression_L1, Z-Score, Sem_Preprocessamento, BOW_Trigram
Executando (52/180): LogisticRegression_L1, Z-Score, Sem_Preprocessamento, TFIDF_Unigram
Executando (53/180): LogisticRegression_L1, Z-Score, Sem_Preprocessamento, TFIDF_Bigram
Executando (54/180): LogisticRegression_L1, Z-Score, Sem_Preprocessamento, TFIDF_Trigram
Executando (55/180): LogisticRegression_L1, Z-Score, Com_Preprocessamento, BOW_Unigram
Executando (56/180): LogisticRegression_L1, Z-Score, Com_Preprocessamento, BOW_Bigram
Executando (57/180): LogisticRegression_L1, Z-Score, Com_Preprocessamento, BOW_Trigram
Executando (58/180): LogisticRegression_L1, Z-Score, Com_Preprocessamento, TFIDF_Unigram
Executando (59/180): LogisticRegression_L1, Z-Score, Com_Preprocessamento, TFIDF_Bigram
Executando (60/180): LogisticRegression_L1, Z-Score, Com_Preprocessamento, TFIDF_Trigram
Executando (61/180): LogisticRegression_L1, MinMax, Sem_Preprocessamento, BOW_Unigram
Executando (62/180): LogisticRegression_L1, MinMax, Sem_Preprocessamento, BOW_Bigram
Executando (63/180): LogisticRegression_L1, MinMax, Sem_Preprocessamento, BOW_Trigram
Executando (64/180): LogisticRegression_L1, MinMax, Sem_Preprocessamento, TFIDF_Unigram
Executando (65/180): LogisticRegression_L1, MinMax, Sem_Preprocessamento, TFIDF_Bigram
Executando (66/180): LogisticRegression_L1, MinMax, Sem_Preprocessamento, TFIDF_Trigram
Executando (67/180): LogisticRegression_L1, MinMax, Com_Preprocessamento, BOW_Unigram
Executando (68/180): LogisticRegression_L1, MinMax, Com_Preprocessamento, BOW_Bigram
Executando (69/180): LogisticRegression_L1, MinMax, Com_Preprocessamento, BOW_Trigram
Executando (70/180): LogisticRegression_L1, MinMax, Com_Preprocessamento, TFIDF_Unigram
Executando (71/180): LogisticRegression_L1, MinMax, Com_Preprocessamento, TFIDF_Bigram
Executando (72/180): LogisticRegression_L1, MinMax, Com_Preprocessamento, TFIDF_Trigram
Executando (73/180): LogisticRegression_L2, NoScaler, Sem_Preprocessamento, BOW_Unigram
Executando (74/180): LogisticRegression_L2, NoScaler, Sem_Preprocessamento, BOW_Bigram
Executando (75/180): LogisticRegression_L2, NoScaler, Sem_Preprocessamento, BOW_Trigram
Executando (76/180): LogisticRegression_L2, NoScaler, Sem_Preprocessamento, TFIDF_Unigram
Executando (77/180): LogisticRegression_L2, NoScaler, Sem_Preprocessamento, TFIDF_Bigram
Executando (78/180): LogisticRegression_L2, NoScaler, Sem_Preprocessamento, TFIDF_Trigram
Executando (79/180): LogisticRegression_L2, NoScaler, Com_Preprocessamento, BOW_Unigram
Executando (80/180): LogisticRegression_L2, NoScaler, Com_Preprocessamento, BOW_Bigram
Executando (81/180): LogisticRegression_L2, NoScaler, Com_Preprocessamento, BOW_Trigram
Executando (82/180): LogisticRegression_L2, NoScaler, Com_Preprocessamento, TFIDF_Unigram
Executando (83/180): LogisticRegression_L2, NoScaler, Com_Preprocessamento, TFIDF_Bigram
Executando (84/180): LogisticRegression_L2, NoScaler, Com_Preprocessamento, TFIDF_Trigram
Executando (85/180): LogisticRegression_L2, Z-Score, Sem_Preprocessamento, BOW_Unigram
Executando (86/180): LogisticRegression_L2, Z-Score, Sem_Preprocessamento, BOW_Bigram
Executando (87/180): LogisticRegression_L2, Z-Score, Sem_Preprocessamento, BOW_Trigram
Executando (88/180): LogisticRegression_L2, Z-Score, Sem_Preprocessamento, TFIDF_Unigram
Executando (89/180): LogisticRegression_L2, Z-Score, Sem_Preprocessamento, TFIDF_Bigram
Executando (90/180): LogisticRegression_L2, Z-Score, Sem_Preprocessamento, TFIDF_Trigram
Executando (91/180): LogisticRegression_L2, Z-Score, Com_Preprocessamento, BOW_Unigram
Executando (92/180): LogisticRegression_L2, Z-Score, Com_Preprocessamento, BOW_Bigram
Executando (93/180): LogisticRegression_L2, Z-Score, Com_Preprocessamento, BOW_Trigram
Executando (94/180): LogisticRegression_L2, Z-Score, Com_Preprocessamento, TFIDF_Unigram
Executando (95/180): LogisticRegression_L2, Z-Score, Com_Preprocessamento, TFIDF_Bigram
Executando (96/180): LogisticRegression_L2, Z-Score, Com_Preprocessamento, TFIDF_Trigram
Executando (97/180): LogisticRegression_L2, MinMax, Sem_Preprocessamento, BOW_Unigram
Executando (98/180): LogisticRegression_L2, MinMax, Sem_Preprocessamento, BOW_Bigram
Executando (99/180): LogisticRegression_L2, MinMax, Sem_Preprocessamento, BOW_Trigram
Executando (100/180): LogisticRegression_L2, MinMax, Sem_Preprocessamento, TFIDF_Unigram
Executando (101/180): LogisticRegression_L2, MinMax, Sem_Preprocessamento, TFIDF_Bigram
Executando (102/180): LogisticRegression_L2, MinMax, Sem_Preprocessamento, TFIDF_Trigram
Executando (103/180): LogisticRegression_L2, MinMax, Com_Preprocessamento, BOW_Unigram
Executando (104/180): LogisticRegression_L2, MinMax, Com_Preprocessamento, BOW_Bigram
Executando (105/180): LogisticRegression_L2, MinMax, Com_Preprocessamento, BOW_Trigram
Executando (106/180): LogisticRegression_L2, MinMax, Com_Preprocessamento, TFIDF_Unigram
Executando (107/180): LogisticRegression_L2, MinMax, Com_Preprocessamento, TFIDF_Bigram
Executando (108/180): LogisticRegression_L2, MinMax, Com_Preprocessamento, TFIDF_Trigram
Executando (109/180): DecisionTree, NoScaler, Sem_Preprocessamento, BOW_Unigram
Executando (110/180): DecisionTree, NoScaler, Sem_Preprocessamento, BOW_Bigram
Executando (111/180): DecisionTree, NoScaler, Sem_Preprocessamento, BOW_Trigram
Executando (112/180): DecisionTree, NoScaler, Sem_Preprocessamento, TFIDF_Unigram
Executando (113/180): DecisionTree, NoScaler, Sem_Preprocessamento, TFIDF_Bigram
Executando (114/180): DecisionTree, NoScaler, Sem_Preprocessamento, TFIDF_Trigram
Executando (115/180): DecisionTree, NoScaler, Com_Preprocessamento, BOW_Unigram
Executando (116/180): DecisionTree, NoScaler, Com_Preprocessamento, BOW_Bigram
Executando (117/180): DecisionTree, NoScaler, Com_Preprocessamento, BOW_Trigram
Executando (118/180): DecisionTree, NoScaler, Com_Preprocessamento, TFIDF_Unigram
Executando (119/180): DecisionTree, NoScaler, Com_Preprocessamento, TFIDF_Bigram
Executando (120/180): DecisionTree, NoScaler, Com_Preprocessamento, TFIDF_Trigram
Executando (121/180): DecisionTree, Z-Score, Sem_Preprocessamento, BOW_Unigram
Executando (122/180): DecisionTree, Z-Score, Sem_Preprocessamento, BOW_Bigram
Executando (123/180): DecisionTree, Z-Score, Sem_Preprocessamento, BOW_Trigram
Executando (124/180): DecisionTree, Z-Score, Sem_Preprocessamento, TFIDF_Unigram
Executando (125/180): DecisionTree, Z-Score, Sem_Preprocessamento, TFIDF_Bigram
Executando (126/180): DecisionTree, Z-Score, Sem_Preprocessamento, TFIDF_Trigram
Executando (127/180): DecisionTree, Z-Score, Com_Preprocessamento, BOW_Unigram
Executando (128/180): DecisionTree, Z-Score, Com_Preprocessamento, BOW_Bigram
Executando (129/180): DecisionTree, Z-Score, Com_Preprocessamento, BOW_Trigram
Executando (130/180): DecisionTree, Z-Score, Com_Preprocessamento, TFIDF_Unigram
Executando (131/180): DecisionTree, Z-Score, Com_Preprocessamento, TFIDF_Bigram
Executando (132/180): DecisionTree, Z-Score, Com_Preprocessamento, TFIDF_Trigram
Executando (133/180): DecisionTree, MinMax, Sem_Preprocessamento, BOW_Unigram
Executando (134/180): DecisionTree, MinMax, Sem_Preprocessamento, BOW_Bigram
Executando (135/180): DecisionTree, MinMax, Sem_Preprocessamento, BOW_Trigram
Executando (136/180): DecisionTree, MinMax, Sem_Preprocessamento, TFIDF_Unigram
Executando (137/180): DecisionTree, MinMax, Sem_Preprocessamento, TFIDF_Bigram
Executando (138/180): DecisionTree, MinMax, Sem_Preprocessamento, TFIDF_Trigram
Executando (139/180): DecisionTree, MinMax, Com_Preprocessamento, BOW_Unigram
Executando (140/180): DecisionTree, MinMax, Com_Preprocessamento, BOW_Bigram
Executando (141/180): DecisionTree, MinMax, Com_Preprocessamento, BOW_Trigram
Executando (142/180): DecisionTree, MinMax, Com_Preprocessamento, TFIDF_Unigram
Executando (143/180): DecisionTree, MinMax, Com_Preprocessamento, TFIDF_Bigram
Executando (144/180): DecisionTree, MinMax, Com_Preprocessamento, TFIDF_Trigram
Executando (145/180): RandomForest, NoScaler, Sem_Preprocessamento, BOW_Unigram
Executando (146/180): RandomForest, NoScaler, Sem_Preprocessamento, BOW_Bigram
Executando (147/180): RandomForest, NoScaler, Sem_Preprocessamento, BOW_Trigram
Executando (148/180): RandomForest, NoScaler, Sem_Preprocessamento, TFIDF_Unigram
Executando (149/180): RandomForest, NoScaler, Sem_Preprocessamento, TFIDF_Bigram
Executando (150/180): RandomForest, NoScaler, Sem_Preprocessamento, TFIDF_Trigram
Executando (151/180): RandomForest, NoScaler, Com_Preprocessamento, BOW_Unigram
Executando (152/180): RandomForest, NoScaler, Com_Preprocessamento, BOW_Bigram
Executando (153/180): RandomForest, NoScaler, Com_Preprocessamento, BOW_Trigram
Executando (154/180): RandomForest, NoScaler, Com_Preprocessamento, TFIDF_Unigram
Executando (155/180): RandomForest, NoScaler, Com_Preprocessamento, TFIDF_Bigram
Executando (156/180): RandomForest, NoScaler, Com_Preprocessamento, TFIDF_Trigram
Executando (157/180): RandomForest, Z-Score, Sem_Preprocessamento, BOW_Unigram
Executando (158/180): RandomForest, Z-Score, Sem_Preprocessamento, BOW_Bigram
Executando (159/180): RandomForest, Z-Score, Sem_Preprocessamento, BOW_Trigram
Executando (160/180): RandomForest, Z-Score, Sem_Preprocessamento, TFIDF_Unigram
Executando (161/180): RandomForest, Z-Score, Sem_Preprocessamento, TFIDF_Bigram
Executando (162/180): RandomForest, Z-Score, Sem_Preprocessamento, TFIDF_Trigram
Executando (163/180): RandomForest, Z-Score, Com_Preprocessamento, BOW_Unigram
Executando (164/180): RandomForest, Z-Score, Com_Preprocessamento, BOW_Bigram
Executando (165/180): RandomForest, Z-Score, Com_Preprocessamento, BOW_Trigram
Executando (166/180): RandomForest, Z-Score, Com_Preprocessamento, TFIDF_Unigram
Executando (167/180): RandomForest, Z-Score, Com_Preprocessamento, TFIDF_Bigram
Executando (168/180): RandomForest, Z-Score, Com_Preprocessamento, TFIDF_Trigram
Executando (169/180): RandomForest, MinMax, Sem_Preprocessamento, BOW_Unigram
Executando (170/180): RandomForest, MinMax, Sem_Preprocessamento, BOW_Bigram
Executando (171/180): RandomForest, MinMax, Sem_Preprocessamento, BOW_Trigram
Executando (172/180): RandomForest, MinMax, Sem_Preprocessamento, TFIDF_Unigram
Executando (173/180): RandomForest, MinMax, Sem_Preprocessamento, TFIDF_Bigram
Executando (174/180): RandomForest, MinMax, Sem_Preprocessamento, TFIDF_Trigram
Executando (175/180): RandomForest, MinMax, Com_Preprocessamento, BOW_Unigram
Executando (176/180): RandomForest, MinMax, Com_Preprocessamento, BOW_Bigram
Executando (177/180): RandomForest, MinMax, Com_Preprocessamento, BOW_Trigram
Executando (178/180): RandomForest, MinMax, Com_Preprocessamento, TFIDF_Unigram
Executando (179/180): RandomForest, MinMax, Com_Preprocessamento, TFIDF_Bigram
Executando (180/180): RandomForest, MinMax, Com_Preprocessamento, TFIDF_Trigram

--- 5. Análise dos Resultados Finais ---
As 15 melhores combinações de modelo e parâmetros, ordenadas por F1-Score:
                      Modelo Normalizador      Preprocessamento Embedding_Ngram  F1_Score_Medio  Precisao_Media  Recall_Medio  Acuracia_Media
0               DecisionTree       MinMax  Com_Preprocessamento   TFIDF_Trigram        0.180000        0.166667           0.2        0.966895
1               DecisionTree     NoScaler  Com_Preprocessamento   TFIDF_Trigram        0.180000        0.166667           0.2        0.966895
2               DecisionTree      Z-Score  Com_Preprocessamento   TFIDF_Trigram        0.180000        0.166667           0.2        0.966895
3   LogisticRegression_NoReg     NoScaler  Sem_Preprocessamento      BOW_Bigram        0.133333        0.200000           0.1        0.975228
4               DecisionTree      Z-Score  Com_Preprocessamento   TFIDF_Unigram        0.133333        0.100000           0.2        0.961377
5      LogisticRegression_L1     NoScaler  Sem_Preprocessamento     BOW_Unigram        0.133333        0.200000           0.1        0.975228
6               DecisionTree       MinMax  Com_Preprocessamento   TFIDF_Unigram        0.133333        0.100000           0.2        0.961377
7               DecisionTree     NoScaler  Com_Preprocessamento   TFIDF_Unigram        0.133333        0.100000           0.2        0.961377
8               DecisionTree       MinMax  Sem_Preprocessamento   TFIDF_Trigram        0.100000        0.100000           0.1        0.964193
9               DecisionTree       MinMax  Sem_Preprocessamento     BOW_Trigram        0.100000        0.100000           0.1        0.972451
10              DecisionTree      Z-Score  Com_Preprocessamento      BOW_Bigram        0.100000        0.100000           0.1        0.972451
11              DecisionTree      Z-Score  Sem_Preprocessamento   TFIDF_Trigram        0.100000        0.100000           0.1        0.964193
12     LogisticRegression_L2     NoScaler  Sem_Preprocessamento      BOW_Bigram        0.100000        0.100000           0.1        0.969711
13     LogisticRegression_L2     NoScaler  Sem_Preprocessamento     BOW_Unigram        0.100000        0.100000           0.1        0.972451
14              DecisionTree      Z-Score  Sem_Preprocessamento     BOW_Trigram        0.100000        0.100000           0.1        0.972451